### PR TITLE
Added mercurial support.

### PR DESCRIPTION
**Pull request by rainydio**
Added mercurial support. Also checking for .git and .hg directories to speed things up. And small changes like $dirty != 0 instead of "$dirty" != "0"

### CODE REVIEW

**Comment by rainydio** [comment]
Also checking added checking for .git and .hg directories to speed things up. And things like $dirty != 0 instead of "$dirty" != "0"

**Comment by rainydio** [comment]
Just realized that I need to check parent dirs for .git and .hg, postponed for now.

**Comment by rainydio** [comment]
Added checking of parent folders

**Comment by inxilpro** [comment]
It seems like there should be a flag that can be set to check for git, mercurial or both.  I don't plan to ever use mercurial, so I'd rather be able to just turn that option off…  Something like:

```
 set fish_prompt_git 1
 set fish_prompt_hg 0
```

…which I could set in my `~/.config/fish/config.fish` file.

Also, there are a couple of typos on the first line of `fish_right_prompt.fish`

**Comment by bobthecow** [comment]
@inxilpro Yes, that's what we should do. But we should use the same env variables as other themes have started standardizing on, so that stuff works across themes :)

https://github.com/oh-my-fish/theme-bobthefish#configuration

In your case,

```
set -g theme_display_git yes
set -g theme_display_hg no
```

**Pull request closed without merging**
